import type { Metadata } from 'next';
import { Raleway, Roboto } from 'next/font/google';
import './globals.css';
import TopBanner from '../components/TopBanner/TopBanner';

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
  display: 'swap',
});

const roboto_mono = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${raleway.variable} ${roboto_mono.variable} antialiased`}>
        <TopBanner>1.800.945.3009</TopBanner>
        {children}
      </body>
    </html>
  );
}
